[2024-12-20T20:08:51.769+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: one_task_dag.one_task manual__2024-12-20T20:08:49.840887+00:00 [queued]>
[2024-12-20T20:08:51.774+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: one_task_dag.one_task manual__2024-12-20T20:08:49.840887+00:00 [queued]>
[2024-12-20T20:08:51.774+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-12-20T20:08:51.784+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): one_task> on 2024-12-20 20:08:49.840887+00:00
[2024-12-20T20:08:51.787+0000] {standard_task_runner.py:57} INFO - Started process 52290 to run task
[2024-12-20T20:08:51.790+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'one_task_dag', 'one_task', 'manual__2024-12-20T20:08:49.840887+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/one_task_dag.py', '--cfg-path', '/tmp/tmp1h2uek_5']
[2024-12-20T20:08:51.791+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask one_task
[2024-12-20T20:08:51.814+0000] {task_command.py:410} INFO - Running <TaskInstance: one_task_dag.one_task manual__2024-12-20T20:08:49.840887+00:00 [running]> on host codespaces-90c33c
[2024-12-20T20:08:52.131+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ilan' AIRFLOW_CTX_DAG_ID='one_task_dag' AIRFLOW_CTX_TASK_ID='one_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-20T20:08:49.840887+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-20T20:08:49.840887+00:00'
[2024-12-20T20:08:52.131+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-20T20:08:52.132+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "hello, linkedin learning!" > /workspaces/hands-on-introdcution-data-engineering-4395021/lab/']
[2024-12-20T20:08:52.139+0000] {subprocess.py:86} INFO - Output:
[2024-12-20T20:08:52.140+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: /workspaces/hands-on-introdcution-data-engineering-4395021/lab/: No such file or directory
[2024-12-20T20:08:52.140+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-20T20:08:52.145+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-20T20:08:52.147+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=one_task_dag, task_id=one_task, execution_date=20241220T200849, start_date=20241220T200851, end_date=20241220T200852
[2024-12-20T20:08:52.156+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task one_task (Bash command failed. The command returned a non-zero exit code 1.; 52290)
[2024-12-20T20:08:52.202+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-20T20:08:52.211+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
